package no.josefus.abuhint.tools

import dev.langchain4j.agent.tool.P
import dev.langchain4j.agent.tool.Tool
import org.springframework.beans.factory.annotation.Value
import java.nio.file.Files

class PowerPointEmailTool(
    private val emailService: EmailService,
    private val powerPointGeneratorTool: PowerPointGeneratorTool,
    @Value("\${resend.pptx-email-template:}") private val pptxEmailTemplate: String
) {

    @Tool(
        "Generer en PowerPoint-presentasjon og send den som vedlegg på e-post. " +
        "Bruk dette når brukeren ønsker å motta eller sende presentasjonen per e-post. " +
        "Lysbildeformatet er identisk med generatePresentation."
    )
    fun generateAndEmail(
        @P("Recipient email address") to: String,
        @P("Title of the presentation") presentationTitle: String,
        @P("Slides in display order. First slide is the cover.") slides: List<Slide>,
        @P("Set to true once the user has confirmed") confirm: Boolean = false
    ): String {
        val fileName = presentationTitle.replace(Regex("[^A-Za-z0-9_-]"), "_").lowercase() + ".pptx"
        if (!confirm) {
            return "I'll generate \"$presentationTitle\" (${slides.size} slides) and email it to $to as an attachment. Confirm to proceed."
        }

        val tempPath = try {
            powerPointGeneratorTool.buildToTempFile(presentationTitle, slides)
        } catch (e: Exception) {
            return "Failed to generate the presentation: ${e.message}"
        }

        return try {
            // Also upload to S3 for a download link in the email body (optional, best-effort)
            val downloadUrl = powerPointGeneratorTool.uploadAndPresign(tempPath, presentationTitle)

            val html = buildEmailHtml(presentationTitle, fileName, downloadUrl)

            emailService.sendEmail(
                html = html,
                to = to,
                attachmentPath = tempPath.toString(),
                attachmentFileName = fileName,
                attachmentContentType = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                confirm = true
            )
        } finally {
            Files.deleteIfExists(tempPath)
        }
    }

    private fun buildEmailHtml(title: String, fileName: String, downloadUrl: String?) = """
        <!doctype html>
        <html>
          <head><meta charset="utf-8"/></head>
          <body style="font-family:Arial,sans-serif;background:#f6f7fb;padding:24px;">
            <div style="max-width:600px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:32px;">
              <h2 style="color:#111827;margin-top:0;">Your PowerPoint is ready</h2>
              <p><strong>$title</strong> is attached to this email as <strong>$fileName</strong>.</p>
              ${if (downloadUrl != null) "<p>You can also <a href=\"$downloadUrl\" style=\"color:#2563eb;\">download $fileName here</a>.</p>" else ""}
              <p style="color:#6b7280;font-size:12px;margin-bottom:0;">Generated by Abuhint</p>
            </div>
          </body>
        </html>
    """.trimIndent()
}
