package no.josefus.abuhint.tools

import dev.langchain4j.agent.tool.P
import dev.langchain4j.agent.tool.Tool
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Component

@Component
class PowerPointEmailTool(
    private val emailService: EmailService,
    private val powerPointGeneratorTool: PowerPointGeneratorTool,
    @Value("\${resend.pptx-email-template:}") private val pptxEmailTemplate: String
) {

    @Tool(
        "Generate a PowerPoint presentation and email it to someone as a download link. " +
        "Use this when the user wants to receive or send the presentation by email. " +
        "The slides format is identical to generatePresentation."
    )
    fun generateAndEmail(
        @P("Recipient email address") to: String,
        @P("Title of the presentation") presentationTitle: String,
        @P("Slides in display order. First slide is the cover.") slides: List<Slide>,
        @P("Set to true once the user has confirmed") confirm: Boolean = false
    ): String {
        val fileName = presentationTitle.replace(Regex("[^A-Za-z0-9_-]"), "_").lowercase() + ".pptx"
        if (!confirm) {
            return "I'll generate \"$presentationTitle\" (${slides.size} slides) and email it to $to. Confirm to proceed."
        }
        val url = powerPointGeneratorTool.buildAndUpload(presentationTitle, slides)
            ?: return "Failed to upload the presentation."
        val html = pptxEmailTemplate.takeIf { it.isNotBlank() }
            ?.replace("{{title}}", presentationTitle)
            ?.replace("{{fileName}}", fileName)
            ?.replace("{{downloadUrl}}", url)
            ?: buildEmailHtml(presentationTitle, fileName, url)
        return emailService.sendEmail(html = html, to = to, confirm = true)
    }

    private fun buildEmailHtml(title: String, fileName: String, downloadUrl: String) = """
        <!doctype html>
        <html>
          <head><meta charset="utf-8"/></head>
          <body style="font-family:Arial,sans-serif;background:#f6f7fb;padding:24px;">
            <div style="max-width:600px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:32px;">
              <h2 style="color:#111827;margin-top:0;">Your PowerPoint is ready</h2>
              <p><strong>$title</strong> is ready as <strong>$fileName</strong>.</p>
              <p><a href="$downloadUrl" style="color:#2563eb;">Download $fileName</a></p>
              <p style="color:#6b7280;font-size:12px;margin-bottom:0;">Generated by Abuhint</p>
            </div>
          </body>
        </html>
    """.trimIndent()
}
